version: 2.1

parameters:
  orb:
    type: string
    description: location of the orb I want to read
    default: "https://raw.githubusercontent.com/jenny-miggin/centralised-config/refs/heads/main/.circleci/frontend-team/frontend-team.yml"
  override-job:
    type: string
    description: name of the orb job to use in the override
    default: "frontend-build"

orbs:
  selected-orb: "<< pipeline.parameters.orb >>"

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: Build my app
          command: echo "Build my app"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: Test my app
          command: echo "Test my app"

workflows:
  build-and-test: 
    jobs:
      - build:
          override-with: selected-orb/<< pipeline.parameters.override-job >>
          type: no-op
      - test:
          requires:
            - build