version: 2.1

setup: true

parameters:
  base-revision:
    type: string
    default: "main"
  output-path:
    type: string
    default: "/tmp/pipeline-parameters.json"

orbs:
  path-filtering: circleci/path-filtering@2.0
  continuation: circleci/continuation@2.0

jobs:
  filter-paths:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - path-filtering/set-parameters:
          # Use the combined path mappings
          mapping: |
            packages/api/.* selected-orb "https://raw.githubusercontent.com/jenny-miggin/centralised-config/refs/heads/main/.circleci/frontend-team/frontend-team.yml"
            packages/api/.* override-job "frontend-build"
          base-revision: << pipeline.parameters.base-revision >>
          output-path: << pipeline.parameters.output-path >>
      - continuation/continue:
          configuration_path: .circleci/central-config.yml
          parameters: << pipeline.parameters.output-path >>


workflows:
  build-and-test: 
    jobs:
      - filter-paths