## This is an orb. To reference it in a centralised config, you need to use the following syntax:
## selected-orb/<< pipeline.parameters.override-build-job >>

version: 2.1

jobs:
  frontend-build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: Build my frontend app
          command: echo "Build my frontend app"
  frontend-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: Deploy my frontend app
          command: |
            echo "Deploy my frontend app" && sleep 300